name: Deploy MangaParty
on:
  push:
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      
      - uses: actions/setup-go@v4
        with: { go-version: '1.22' }

      - uses: goreleaser/goreleaser-action@v5
        with:
          version: '~> v2'
          args: build --snapshot --clean --single-target
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          # Step 1: Deploy Binary (strip dist path)
          source: "dist/mangaparty_linux_amd64_v1/mangaparty"
          target: "/var/www/mangaparty/"
          # strips 'dist' and 'mangaparty_linux_amd64_v1'
          strip_components: 2

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          # Step 2: Deploy Assets (preserve structure)
          source: "templates,static,sql"
          target: "/var/www/mangaparty/"
          strip_components: 0

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            chmod +x /var/www/mangaparty/mangaparty
            systemctl restart mangaparty